language: go

go:
  - '1.16'
  - '1.17'

script:
  - export GO111MODULE=on CGO_ENABLED=1 GOROOT=$(go env GOROOT)
  - mkdir -p $HOME/.config/kustomize && ln -s $PWD/plugin $HOME/.config/kustomize/
  - make test
